apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: printing-system
type: Opaque
# Values are base64-encoded: echo -n "value" | base64
data:
  username: cGdhZG1pbg==           # pgadmin
  password: bWVvd21lb3dtZW93X0Jhb2Jhb01lb3chNDIz   # meowmeowmeow_BaobaoMeow!423
  connection-string: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT0zZGRiO1VzZXJuYW1lPXBnYWRtaW47UGFzc3dvcmQ9bWVvd21lb3dtZW93X0Jhb2Jhb01lb3chNDIz
