apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data-pvc
  namespace: printing-system
spec:
  accessModes:
    - ReadWriteOnce   # minikube: standard storage class supports only RWO
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
