apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: printing-system
type: Opaque
# echo -n "value" | base64
data:
  # Connection string: Host=postgres;Database=3ddb;Username=pgadmin;Password=meowmeowmeow_BaobaoMeow!423
  ConnectionStrings__DataContext: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT0zZGRiO1VzZXJuYW1lPXBnYWRtaW47UGFzc3dvcmQ9bWVvd21lb3dtZW93X0Jhb2Jhb01lb3chNDIz
  # JWT Key: 3DPrintingSystemSecretKey_MinLength32!!
  Jwt__Key: M0RQcmludGluZ1N5c3RlbVNlY3JldEtleV9NaW5MZW5ndGgzMiEh
