apiVersion: v1
kind: Service
metadata:
  name: api-3d
  namespace: printing-system
spec:
  selector:
    app: api-3d
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080   # доступний ззовні на порту 30080
  type: NodePort        # для локального тестування; змінити на LoadBalancer для хмари
